# Generated by Django 6.1.1 on 2026-09-24 18:19

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Inventory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "public_id",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                ("name", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True)),
                ("default_currency", models.CharField(default="USD", max_length=3)),
                (
                    "inventory_type",
                    models.CharField(
                        choices=[
                            ("personal", "Personal"),
                            ("home", "Home"),
                            ("business", "Business"),
                            ("estate", "Estate"),
                            ("collection", "Collection"),
                            ("other", "Other"),
                        ],
                        default="personal",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("archived_at", models.DateTimeField(blank=True, null=True)),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="inventories",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "public_id",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                ("name", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("archived_at", models.DateTimeField(blank=True, null=True)),
                (
                    "inventory",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="categories",
                        to="myapp.inventory",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Item",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "public_id",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                ("name", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True)),
                ("brand", models.CharField(blank=True, max_length=255)),
                ("model_number", models.CharField(blank=True, max_length=255)),
                ("serial_number", models.CharField(blank=True, max_length=255)),
                (
                    "condition",
                    models.CharField(
                        choices=[
                            ("new", "New"),
                            ("like_new", "Like New"),
                            ("used", "Used"),
                            ("damaged", "Damaged"),
                            ("unknown", "Unknown"),
                        ],
                        default="unknown",
                        max_length=20,
                    ),
                ),
                ("quantity", models.PositiveIntegerField(default=1)),
                ("purchase_date", models.DateField(blank=True, null=True)),
                (
                    "purchase_amount",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=12, null=True
                    ),
                ),
                (
                    "current_estimated_amount",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=12, null=True
                    ),
                ),
                (
                    "manual_value",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=12, null=True
                    ),
                ),
                ("valuation_date", models.DateTimeField(blank=True, null=True)),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("archived_at", models.DateTimeField(blank=True, null=True)),
                (
                    "category",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="items",
                        to="myapp.category",
                    ),
                ),
                (
                    "inventory",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="myapp.inventory",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Attachment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "public_id",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                ("file", models.FileField(upload_to="item_attachments/%Y/%m/")),
                (
                    "file_type",
                    models.CharField(
                        choices=[
                            ("photo", "Photo"),
                            ("receipt", "Receipt"),
                            ("warranty", "Warranty"),
                            ("appraisal", "Appraisal"),
                            ("other", "Other"),
                        ],
                        default="photo",
                        max_length=20,
                    ),
                ),
                ("original_filename", models.CharField(blank=True, max_length=255)),
                ("mime_type", models.CharField(blank=True, max_length=100)),
                ("file_size", models.PositiveBigIntegerField(blank=True, null=True)),
                ("is_primary", models.BooleanField(default=False)),
                ("uploaded_at", models.DateTimeField(auto_now_add=True)),
                ("archived_at", models.DateTimeField(blank=True, null=True)),
                (
                    "item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attachments",
                        to="myapp.item",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Location",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "public_id",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                ("name", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("archived_at", models.DateTimeField(blank=True, null=True)),
                (
                    "inventory",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="locations",
                        to="myapp.inventory",
                    ),
                ),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="sub_locations",
                        to="myapp.location",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="item",
            name="location",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="items",
                to="myapp.location",
            ),
        ),
        migrations.CreateModel(
            name="ValuationRun",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "public_id",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                (
                    "valuation_type",
                    models.CharField(
                        choices=[
                            ("automated", "Automated"),
                            ("manual", "Manual"),
                            ("appraisal", "Appraisal"),
                        ],
                        default="automated",
                        max_length=20,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("running", "Running"),
                            ("success", "Success"),
                            ("partial", "Partial"),
                            ("failed", "Failed"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                (
                    "estimated_amount",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=12, null=True
                    ),
                ),
                ("currency", models.CharField(default="USD", max_length=3)),
                (
                    "range_low",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=12, null=True
                    ),
                ),
                (
                    "range_high",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=12, null=True
                    ),
                ),
                ("confidence_bps", models.PositiveIntegerField(blank=True, null=True)),
                ("sample_count", models.PositiveIntegerField(blank=True, null=True)),
                ("algorithm_version", models.CharField(blank=True, max_length=50)),
                ("input_snapshot", models.JSONField(blank=True, default=dict)),
                ("error_code", models.CharField(blank=True, max_length=50)),
                ("error_message", models.TextField(blank=True)),
                ("requested_at", models.DateTimeField(auto_now_add=True)),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="valuation_runs",
                        to="myapp.item",
                    ),
                ),
                (
                    "requested_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="requested_valuations",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ValuationSourceResult",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("source", models.CharField(max_length=100)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("success", "Success"),
                            ("failed", "Failed"),
                            ("skipped", "Skipped"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("results_found", models.PositiveIntegerField(default=0)),
                ("results_used", models.PositiveIntegerField(default=0)),
                (
                    "source_estimate",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=12, null=True
                    ),
                ),
                ("currency", models.CharField(default="USD", max_length=3)),
                ("error_code", models.CharField(blank=True, max_length=50)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "valuation_run",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="source_results",
                        to="myapp.valuationrun",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ComparableListing",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("external_listing_id", models.CharField(blank=True, max_length=255)),
                ("url", models.URLField(blank=True, max_length=2048)),
                ("title", models.CharField(max_length=512)),
                (
                    "price",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=12, null=True
                    ),
                ),
                (
                    "shipping",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=12, null=True
                    ),
                ),
                ("currency", models.CharField(default="USD", max_length=3)),
                ("condition_raw", models.CharField(blank=True, max_length=100)),
                ("condition_normalized", models.CharField(blank=True, max_length=100)),
                ("observed_at", models.DateTimeField(blank=True, null=True)),
                ("included_in_estimate", models.BooleanField(default=True)),
                ("exclusion_reason", models.TextField(blank=True)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "source_result",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="comparable_listings",
                        to="myapp.valuationsourceresult",
                    ),
                ),
            ],
        ),
        migrations.AddIndex(
            model_name="inventory",
            index=models.Index(
                fields=["owner", "archived_at"], name="inv_owner_arch_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="inventory",
            constraint=models.UniqueConstraint(
                condition=models.Q(("archived_at__isnull", True)),
                fields=("owner", "name"),
                name="unique_active_inventory_name",
            ),
        ),
        migrations.AddConstraint(
            model_name="category",
            constraint=models.UniqueConstraint(
                condition=models.Q(("archived_at__isnull", True)),
                fields=("inventory", "name"),
                name="unique_active_category",
            ),
        ),
        migrations.AddConstraint(
            model_name="attachment",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("is_primary", False), ("file_type", "photo"), _connector="OR"
                ),
                name="primary_attachment_is_photo",
            ),
        ),
        migrations.AddConstraint(
            model_name="attachment",
            constraint=models.UniqueConstraint(
                condition=models.Q(
                    ("archived_at__isnull", True),
                    ("file_type", "photo"),
                    ("is_primary", True),
                ),
                fields=("item",),
                name="one_active_primary_photo",
            ),
        ),
        migrations.AddConstraint(
            model_name="location",
            constraint=models.UniqueConstraint(
                condition=models.Q(
                    ("archived_at__isnull", True), ("parent__isnull", True)
                ),
                fields=("inventory", "name"),
                name="unique_active_root_location",
            ),
        ),
        migrations.AddConstraint(
            model_name="location",
            constraint=models.UniqueConstraint(
                condition=models.Q(
                    ("archived_at__isnull", True), ("parent__isnull", False)
                ),
                fields=("inventory", "parent", "name"),
                name="unique_active_child_location",
            ),
        ),
        migrations.AddIndex(
            model_name="item",
            index=models.Index(
                fields=["inventory", "archived_at", "-updated_at"],
                name="item_inv_arch_upd_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="item",
            constraint=models.CheckConstraint(
                condition=models.Q(("quantity__gte", 1)), name="item_qty_gte_1"
            ),
        ),
        migrations.AddIndex(
            model_name="valuationrun",
            index=models.Index(
                fields=["item", "-requested_at"], name="valuation_item_req_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="valuationrun",
            index=models.Index(
                fields=["status", "requested_at"], name="valuation_status_req_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="valuationrun",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("confidence_bps__isnull", True),
                    models.Q(
                        ("confidence_bps__gte", 0), ("confidence_bps__lte", 10000)
                    ),
                    _connector="OR",
                ),
                name="valuation_confidence_valid",
            ),
        ),
        migrations.AddConstraint(
            model_name="valuationrun",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("range_low__isnull", True),
                    ("range_high__isnull", True),
                    ("range_low__lte", models.F("range_high")),
                    _connector="OR",
                ),
                name="valuation_range_ordered",
            ),
        ),
        migrations.AddConstraint(
            model_name="valuationsourceresult",
            constraint=models.UniqueConstraint(
                fields=("valuation_run", "source"), name="one_source_per_valuation_run"
            ),
        ),
        migrations.AddConstraint(
            model_name="valuationsourceresult",
            constraint=models.CheckConstraint(
                condition=models.Q(("results_used__lte", models.F("results_found"))),
                name="source_used_lte_found",
            ),
        ),
    ]
