"""Shared mock records used by the frontend pages."""

INVENTORY_ITEMS = [
    {
        "id": 1,
        "name": "Canon EOS R6",
        "category": "Electronics",
        "location": "Office",
        "estimated_value": 1850,
        "status": "Current",
        "icon": "photo_camera",
    },
    {
        "id": 2,
        "name": "Seiko Prospex",
        "category": "Watches",
        "location": "Bedroom",
        "estimated_value": 725,
        "status": "Review",
        "icon": "watch",
    },
    {
        "id": 3,
        "name": "MacBook Pro",
        "category": "Electronics",
        "location": "Office",
        "estimated_value": 1250,
        "status": "Current",
        "icon": "laptop_mac",
    },
    {
        "id": 4,
        "name": "Lake Painting",
        "category": "Art",
        "location": "Living Room",
        "estimated_value": 475,
        "status": "Current",
        "icon": "image",
    },
    {
        "id": 5,
        "name": "Leather Couch",
        "category": "Furniture",
        "location": "Living Room",
        "estimated_value": 2100,
        "status": "Current",
        "icon": "chair",
    },
    {
        "id": 6,
        "name": "Titleist Golf Clubs",
        "category": "Sports",
        "location": "Garage",
        "estimated_value": 850,
        "status": "Review",
        "icon": "sports_golf",
    },
    {
        "id": 7,
        "name": "Vintage Record Player",
        "category": "Collectibles",
        "location": "Living Room",
        "estimated_value": 620,
        "status": "Current",
        "icon": "album",
    },
    {
        "id": 8,
        "name": "Hiking Backpack",
        "category": "Outdoor",
        "location": "Garage",
        "estimated_value": 220,
        "status": "Current",
        "icon": "backpack",
    },
]

_VALUATION_DETAILS = {
    1: {
        "current_value": 1850,
        "last_updated": "1 day ago",
        "days_old": 1,
        "status": "Needs Review",
    },
    2: {
        "current_value": 725,
        "last_updated": "9 days ago",
        "days_old": 9,
        "status": "Current",
    },
    3: {
        "current_value": 1290,
        "last_updated": "14 days ago",
        "days_old": 14,
        "status": "Current",
    },
    6: {
        "current_value": 850,
        "last_updated": "72 days ago",
        "days_old": 72,
        "status": "Needs Review",
    },
    7: {
        "current_value": 520,
        "last_updated": "105 days ago",
        "days_old": 105,
        "status": "Needs Review",
    },
    5: {
        "current_value": 2100,
        "last_updated": "88 days ago",
        "days_old": 88,
        "status": "Needs Review",
    },
}

CATEGORY_SUMMARIES = [
    {
        "id": 1,
        "name": "Electronics",
        "description": "Computers, cameras, televisions, and other electronics.",
        "item_count": 34,
        "total_value": 12450,
        "updated": "Updated 2d ago",
        "updated_days": 2,
        "icon": "laptop_mac",
        "icon_background": "#dbeafe",
        "icon_color": "#1d4ed8",
    },
    {
        "id": 2,
        "name": "Watches",
        "description": "Watches and timepieces.",
        "item_count": 12,
        "total_value": 5800,
        "updated": "Updated 5d ago",
        "updated_days": 5,
        "icon": "watch",
        "icon_background": "#ede9fe",
        "icon_color": "#4338ca",
    },
    {
        "id": 3,
        "name": "Collectibles",
        "description": "Collectibles, memorabilia, and specialty items.",
        "item_count": 18,
        "total_value": 3420,
        "updated": "Updated 1w ago",
        "updated_days": 7,
        "icon": "collections",
        "icon_background": "#fef3c7",
        "icon_color": "#ca8a04",
    },
    {
        "id": 4,
        "name": "Sports",
        "description": "Sports equipment and related belongings.",
        "item_count": 9,
        "total_value": 1875,
        "updated": "Updated 4d ago",
        "updated_days": 4,
        "icon": "emoji_events",
        "icon_background": "#dcfce7",
        "icon_color": "#15803d",
    },
    {
        "id": 5,
        "name": "Furniture",
        "description": "Furniture and household furnishings.",
        "item_count": 15,
        "total_value": 6200,
        "updated": "Updated 3d ago",
        "updated_days": 3,
        "icon": "chair",
        "icon_background": "#fee2e2",
        "icon_color": "#b4534b",
    },
    {
        "id": 6,
        "name": "Art",
        "description": "Artwork, paintings, and decorative pieces.",
        "item_count": 7,
        "total_value": 2950,
        "updated": "Updated 6d ago",
        "updated_days": 6,
        "icon": "palette",
        "icon_background": "#ede9fe",
        "icon_color": "#4338ca",
    },
]

_INVENTORY_ITEMS_BY_ID = {item["id"]: item for item in INVENTORY_ITEMS}
VALUATION_ITEMS = [
    {**_INVENTORY_ITEMS_BY_ID[item_id], **details}
    for item_id, details in _VALUATION_DETAILS.items()
]

AI_PREVIEW = {
    "name": "Canon EOS R6",
    "current_estimate": 1850,
    "range_low": 1700,
    "range_high": 2000,
    "confidence": "High",
    "sources": [
        {"name": "B&H Photo", "value": 1899},
        {"name": "Amazon", "value": 1750},
        {"name": "KEH Camera", "value": 1850},
        {"name": "MPB", "value": 1795},
    ],
}
